### ISSUE TITLE
Get current duration of live stream

### ISSUE THREAD

**Issue by Mcrich23** [b5i/YouTubeKit#10]
I would like to get how long a live stream has been going on for.

**Comment by b5i** [comment]
Hello, thanks for trying out YouTubeKit!

> I would like to get how long a live stream has been going on for.

I'll do more research soon but for the moment the only way you can get this information is with the [`timePosted`](https://swiftpackageindex.com/b5i/YouTubeKit/v1.1.1/documentation/youtubekit) property of `YTVideo`. It won't give you the precise time when the livestream started but a string describing it.

**Comment by b5i** [comment]
After a few checks, it is not possible to know precisely when a livestream has started.
