### ISSUE TITLE
Get comments

### ISSUE THREAD

**Issue by Mcrich23** [b5i/YouTubeKit#12]
How do I get more comments than just the teaser?

**Comment by b5i** [comment]
Hello, that's a feature that is coming very soon to YouTubeKit. In the meantime you can get them using another repository or by trying to create your own request as explained in the README (I'll be glad to answer your questions if you do it this way).

**Comment by b5i** [comment]
Added in [`b5ad965`](https://github.com/b5i/YouTubeKit/commit/b5ad96559d35916630711aa4caa8a425764a1195).
