### ISSUE TITLE
Get likes

### ISSUE THREAD

**Issue by Mcrich23** [b5i/YouTubeKit#13]
Please add it so I can get if the user has already liked the video.

**Comment by b5i** [comment]
Hello, this information is already present in the `authenticatedInfos` of `MoreVideoInfosResponse`.

**Comment by Mcrich23** [comment]
It does, but it does not say if the **user** has liked the video.

**Comment by b5i** [comment]
> It does, but it does not say if the **user** has liked the video.

Yes it does, what do you get as a

**Comment by Mcrich23** [comment]
I figured it out, thank you.
