### ISSUE TITLE
How to use contentContinuation for channels

### ISSUE THREAD

**Issue by Mcrich23** [b5i/YouTubeKit#15]
How do I use `ChannelInfosResponse`'s `getChannelContentContinuation` method? I cannot figure out how to properly pass in `ChannelContent`

**Comment by b5i** [comment]
Hello, you have to pass the type of the content that you want to fetch e.g. `ChannelInfosResponse.Playlists.self`. If you want to see it in action [here](https://github.com/b5i/Atwy/blob/86ae813c9652048c3a45c1bcf9a10afda18b01e9/Atwy/ChannelDetailsView.swift#L298).

**Comment by Mcrich23** [comment]
Thank you!
