### ISSUE TITLE
Request: Get trending videos

### ISSUE THREAD

**Issue by Mcrich23** [b5i/YouTubeKit#19]
Just that, getting the trending videos like you do the home screen

**Comment by b5i** [comment]
Hello, that’s also a feature in the roadmap of YouTubeKit and it’s coming for the v3 redesign of Atwy (coming soon).

**Comment by b5i** [comment]
Added in [`5960b78`](https://github.com/b5i/YouTubeKit/commit/5960b78932ff5e444c29653337e93f9085c8811b).
