### ISSUE TITLE
Request: Add captions

### ISSUE THREAD

**Issue by Mcrich23** [b5i/YouTubeKit#20]
I think fetching the srt closed captions would be a fantastic feature!

**Comment by b5i** [comment]
Hello! Indeed having the closed captions (I suppose that you mean the ones that aren't present in the HLS stream?) would definitely be cool! This feature is also in the roadmap but a bit farther than some others you mentioned. If you want to try to develop your own request for captions I'll be glad to help you to do so! (Or just wait and I'll add it!)

**Comment by b5i** [comment]
Added in [`b540770`](https://github.com/b5i/YouTubeKit/commit/b54077017c204ad31f0b74a797af92679be86045).
