### ISSUE TITLE
How do I re-order playlist videos?

### ISSUE THREAD

**Issue by Mcrich23** [b5i/YouTubeKit#21]
I have looked at Atwy, and I cannot figure out this feature. How do I re-arrange the videos?

Here is my current code and it always responds disconnected: 
```
func moveVideoInPlaylist(for playlistId: String, moving sourceVideoId: String, toBefore destinationVideoId: String?) async throws {
    var data: [HeadersList.AddQueryInfo.ContentTypes : String] = [.movingVideoId: sourceVideoId, .browseId: playlistId]
        
    if let destinationVideoId {
        data[.videoBeforeId] = destinationVideoId
    }
        
    let (response, error) = await MoveVideoInPlaylistResponse.sendRequest(youtubeModel: entryPoint, data: data)
    if let error {
        print(error)
        throw error
    }
        
    guard let response else {
        throw APIError.networkError(NSError(domain: "", code: -2, userInfo: nil))
    }
        
    print(response)
}
```

**Comment by Mcrich23** [comment]
I think there is an issue where `AuthenticatedResponse` isn't working, because like/dislike is also not working

**Comment by b5i** [comment]
> I have looked at Atwy, and I cannot figure out this feature. How do I re-arrange the videos?
> 
> Here is my current code and it always responds disconnected:
> 
> ```
> func moveVideoInPlaylist(for playlistId: String, moving sourceVideoId: String, toBefore destinationVideoId: String?) async throws {
>     var data: [HeadersList.AddQueryInfo.ContentTypes : String] = [.movingVideoId: sourceVideoId, .browseId: playlistId]
>         
>     if let destinationVideoId {
>         data[.videoBeforeId] = destinationVideoId
>     }
>         
>     let (response, error) = await MoveVideoInPlaylistResponse.sendRequest(youtubeModel: entryPoint, data: data)
>     if let error {
>         print(error)
>         throw error
>     }
>         
>     guard let response else {
>         throw APIError.networkError(NSError(domain: "", code: -2, userInfo: nil))
>     }
>         
>     print(response)
> }
> ```

Hello, could you check if your playlistID has "VL" as a prefix? If it has you should remove it from the playlistId that you give to the `MoveVideoInPlaylistResponse`. Let me know once you tested that.

**Comment by b5i** [comment]
> I think there is an issue where `AuthenticatedResponse` isn't working, because like/dislike is also not working

That's probably because you haven't updated your fork, I made a fix a few days ago. Let me know it is still doesn't work.

**Comment by Mcrich23** [comment]
figured it out, ty
