### ISSUE TITLE
Resolution - Supports getting video urls in many different qualities

### ISSUE THREAD

**Issue by hoangnam714** [b5i/YouTubeKit#22]
Is it possible for you to support retrieving videos in many different qualities?

**Comment by b5i** [comment]
Yes, you can use the `VideoInfosWithDownloadFormatsResponse` to retrieve many different formats. Just be aware that some of them are video/audio only and you would need to merge two of them.

**Comment by hoangnam714** [comment]
I do see fetchAllPossibleHostPlaylistsThrowing, but i tried using this func but after calling it it seems to be stuck here, nothing is returned, 
Can you help me see where I went wrong?
<img width="1145" alt="image" src="https://github.com/b5i/YouTubeKit/assets/51524705/ebb56532-8fb9-40dc-9461-7d36554b7a81">

**Comment by b5i** [comment]
It seems like there was an error thrown during the process that is handled by `Task`, probably because you didn't provide any cookies or that they aren't valid. 
The method `fetchAllPossibleHostPlaylistsThrowing` fetches all the playlists that the account of the provided cookies has and indicates whether the video is already in it or not. If you want to fetch the formats you should use is `fetchStreamingInfosThrowing`, let me know if you have any other questions!

**Comment by hoangnam714** [comment]
Can you give me a specific example, in my case, I have 1 video ID, I want to have urls for each video quality to use for each network condition
<img width="1146" alt="image" src="https://github.com/b5i/YouTubeKit/assets/51524705/ecfebe84-99dd-4e5b-ac74-04a7e51884e1">

**Comment by b5i** [comment]
You should probably delete your comment as it contains an image with some cookies and I don't think it's safe to put them on the Internet available to everyone.

For archives here is the message:

> Can you give me a specific example, in my case, I have 1 video ID, I want to have urls for each video quality to use for each network condition

The tests contain an example [here](https://github.com/b5i/YouTubeKit/blob/faa3c1a46d32887f3e30dc78692d6e4841da7572/Tests/YouTubeKitTests/YouTubeKitTests.swift#L487). In it, two YTVideos are instantiated with the videoId as their only property, you can do as in the test or manually use the `VideoInfosWithDownloadFormatsResponse` this way 
```swift
let formatsResponse = try await VideoInfosWithDownloadFormatsResponse.sendThrowingRequest(
            youtubeModel: youtubeModel,
            data: [.query: videoId],
            useCookies: true)
```

**Comment by hoangnam714** [comment]
> Yes, you can use the `VideoInfosWithDownloadFormatsResponse` to retrieve many different formats. Just be aware that some of them are video/audio only and you would need to merge two of them.

Sorry to bother you, but is there a faster way to merge video and audio into one url, similar to VideoInfosWithDownloadFormatsResponse.videoInfos.streamingURL, because I'm using AVplayer to play video, if I merge I will have to fix a lot of things.
I am very grateful for your help
