### ISSUE TITLE
[BUG] - I cannot download the YouTube videos from some video stream URLs 

### ISSUE THREAD

**Issue by DanielCrompton123** [b5i/YouTubeKit#23]
I am using a function to download a video at a specific URL which relies on YouTubeKit:

```
    func download(to directoryURL: URL) async {
        downloading = true
        defer { downloading = false }
        
        // Make sure thre URL exists
        if videoURL.isEmpty {
            error = "Please provide a URL"
            return
        }
        guard let url =  URL(string: videoURL) else {
            error = "Could not parse you input to a URL"
            return
        }
        
        // Make the YouTube video
        let video = YouTube(url: url)
        guard let videoTitle = try? await video.metadata?.title else {
            self.error = "Could not get video title"
            return
        }
        // get the streams and filter for highest resolution
        do {
            let streams = try await video.streams
            
            guard let stream = audioOnly ? streams.highestAudioBitrateStream() : streams.highestResolutionStream() else {
                self.error = "Could not get the highest stream resolution"
                return
            }
            
            // Download the video
            let url = stream.url
            print("URL is \(url.absoluteString)")
            
            do {
                let (data, _) = try await URLSession.shared.data(from: url)
                let fileURL = directoryURL.appendingPathComponent(videoTitle, conformingTo: audioOnly ? .mpeg4Audio : .mpeg4Movie)
                print("File URL = \(fileURL.relativePath)")
                try! data.write(to: fileURL)
                print("SUCCESS!")
            } catch {
                self.error = "Could not write the video data to disk"
            }
            
        } catch {
            self.error = "Could not get video streams"
        }
    }
```

**However when `videoURL = "https://www.youtube.com/watch?v=byrRbWGN1Nk&t=2s"` the `url` links gives me a 403 code which of course means the video cannot be downloaded.**

**However with other videos, eg: `https://www.youtube.com/watch?v=kOf54RdoH7A` the video will download.**

You mentioned this project corresponds somewhat with Pytube for Python: I tested the same (broken) video URL with Pytube on Python and the video URLs both libraries gave were similar but different.
Here is the video URL from YouTubeKit (https://www.youtube.com/watch?v=byrRbWGN1Nk&t=2s): `https://rr4---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1717471505&ei=sTReZu2JGLXYxN8P9IStmAc&ip=2a00%3A23c6%3A8916%3A4601%3A3ccd%3A97d2%3A584%3Ab609&id=o-AMh2onJ7kBeM1TcBSzEH3AHwi3RxBvc1g5MIfnOf5w_f&itag=313&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=na&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-auod&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=44&initcwndbps=2188750&bui=AbKP-1OvLtwCb4L6dwT1GMEbkK3ZrL7X3gxm7Jk2uN3SPgdGh3yM2NERxfv-OI8gbvJZsqTLa-8SccZ_&spc=UWF9fxsIyYb90o96SI929OsJfiC5ftcu7cmAbYWrLrXY1meJws4thG_mk5sC&vprv=1&svpuc=1&mime=video%2Fwebm&ns=c1SX90TtWbl62x8S5MhcphYQ&rqh=1&gir=yes&clen=41458899&dur=251.920&lmt=1634000891472896&mt=1717449442&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=6216224&n=G66MYAPZ87IsYsFCO&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAMO0Pdosml7oxsuppKGIpKLSussPwkE7nwdrtEVXBNyFAiEA2EKgHHo4d0MUPosLPhHQZryODpoMejeeHDj1yNr_F9k%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRgIhAPNn3zf-pAHhlEGjbsrVn7fjeWZ0fOVcUepyieRln2iMAiEAuHEKzTdThDUEtTrWVe64qgB6GWv-DFsAZZJcOXn9YWM%3D` and here it is from Pytube: `https://rr4---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1717471554&ei=4jReZrKbB8eKmLAPm-u2qAQ&ip=2a00%3A23c6%3A8916%3A4601%3A3ccd%3A97d2%3A584%3Ab609&id=o-ANagADo5V_Hh4UtyXzzaZEFTX4S4ekFAI4OaX1uxc1L9&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=na&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-auod&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=44&initcwndbps=2191250&bui=AbKP-1MGBozmWktaGcxs8nIzz7TRKbdAbxOSv-yL2rwxjGZlrF2wxZLfga6IxX3NSWnT47RiiUXRARtC&vprv=1&mime=video%2Fmp4&rqh=1&cnr=14&ratebypass=yes&dur=251.982&lmt=1634000896163657&mt=1717449687&fvip=4&c=ANDROID_EMBEDDED_PLAYER&txp=6211224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Cmime%2Crqh%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAJ1MSgLtyxWxLnQobNiRgFntwlN3p-oJ0RzqPxHknq4zAiBcbtfpxkSFvMYRtmMl2JyFp9KfhpXkOIDZRAm5fy_TCw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgdi5NBPdmU2IOAQCFBTY_2Mr_kZLFu3NUh1aZ9jICM1cCIQCgrRs5TdeaLnJ4wq40U9Ni8nPgOJQ6qONtLzWwdJ67Zw%3D%3D`.

Hope this helps.

**Comment by b5i** [comment]
Hello! I'm not sure if you're talking about the right YouTubeKit project (maybe [this](https://github.com/alexeichhorn/YouTubeKit)?) because I'm not really relying on pytube for the API and I don't recognize the calls that you do in the code you provided. Can you make sure that b5i/YouTubeKit is the right repository that you used in your project?

Thanks

Antoine

**Comment by DanielCrompton123** [comment]
Hello b5i I am so sorry about this, you are correct. Thank you so much for pointing me to the correct API. My confusion arose from 2 packages with the same name!
