### ISSUE TITLE
HomeScreenResponse empty result

### ISSUE THREAD

**Issue by 666bsw** [b5i/YouTubeKit#25]
Hello!
how to get home screen correctly?

let result = try await HomeScreenResponse.sendThrowingRequest(youtubeModel: YTM, data: [.])

I get an empty result.

**Comment by b5i** [comment]
Hello! YouTube stopped providing videos from the Home Screen a few months ago and you need to provide cookies to the `YouTubeModel` for it to work (you can do the test yourself by opening a private browsing window and go to their website). I'm going to add the trending videos requests  soon and that might replace the `HomeScreenResponse`.
