### ISSUE TITLE
HomeScreenResponse always empty answer

### ISSUE THREAD

**Issue by 666bsw** [b5i/YouTubeKit#26]
HomeScreenResponse always empty answer
what is needed in this request to get a list of videos?

**Comment by b5i** [comment]
> HomeScreenResponse always empty answer

Hello! You can take a look at my explanation in [this issue](https://github.com/b5i/YouTubeKit/issues/25#issuecomment-2188829714).

> what is needed in this request to get a list of videos?

You need to provide some cookies from a google account. Alternatively, you can opt to use the `TrendingVideosResponse` to get some videos.

**Comment by 666bsw** [comment]
Hi!
got it, thanks for the quick reply!!

**Comment by 666bsw** [comment]
can you give an example of constructing a TrendingVideosResponse query ?
for example for music?

**Comment by b5i** [comment]
> can you give an example of constructing a TrendingVideosResponse query ?
> 
> for example for music?

Hello! You can use the same code as the tests use ([here](https://github.com/b5i/YouTubeKit/blob/d2a2220596141f61f7200578d19eb8e4ea74855e/Tests/YouTubeKitTests/YouTubeKitTests.swift#L1129)). 

As YouTube doesn't use fixed endpoints for their trending categories, YouTubeKit won't give you the constants (`requestParams`) as they could change anytime. However, you can try to do the request once and save the token for the music tab and reuse it in the future if you're willing to take the risk of getting an empty value if they change the parameter.
