### ISSUE TITLE
SearchResponse not working

### ISSUE THREAD

**Issue by 666bsw** [b5i/YouTubeKit#29]
stopped working today   SearchResponse

test code:
```
func fetchRequest(request: String) async {
        do {
            let result = try await SearchResponse.sendThrowingRequest(youtubeModel: ytm, data: [.query: request])
            print(result)
        } catch {
            print(error.localizedDescription)
        }
}
```

answer: 
The operation couldn’t be completed. (MusicRadioEq.NetworkError error 1.)

code that worked yesterday:
```
private func requestToken(token: String) async -> ([any YTSearchResult], String) {
        let dataParameters: [HeadersList.AddQueryInfo.ContentTypes : String] = [
            .query: token
        ]
        let responce: SearchResponse? = try? await SearchResponse.sendThrowingRequest(youtubeModel: ytm, data: dataParameters)
        let results: [any YTSearchResult] = responce?.results ?? []
        let continuationToken: String = responce?.continuationToken ?? ""
        return (results, continuationToken)
}
```

answer: 

11.3.0 - [FirebasePerformance][I-PRF100009] Logging network request trace - https://www.youtube.com/youtubei/v1/search, Response code: 400, 523.9340ms

iOS, xCode and framework versions - latest

**Comment by b5i** [comment]
Hello, thank you for raising this issue!
Could you give me the contents of the response 400 given by YouTube and more details about the error in the first example please (I only see an error with the name of your project?)?

**Comment by 666bsw** [comment]
Hello!
Today it works fast and well again!
Sorry for the disturbance)
Maybe there was some kind of problem with the operator.
Best regards

answer:
11.3.0 - [FirebasePerformance][I-PRF300005] URL length exceeds limits, truncating recorded URL - https://www.youtube.com/youtubei/v1/search.
11.3.0 - [FirebasePerformance][I-PRF100009] Logging network request trace - https://www.youtube.com/youtubei/v1/search, **Response code: 200, 1676.3790ms**
