### ISSUE TITLE
[BUG] - Log in with a multi-channel account and an error loading videos in the playlist.

### ISSUE THREAD

**Issue by tienmanhsc92** [b5i/YouTubeKit#30]
If a YouTube account has 2 channels, how can you switch between those channels? Currently unable to retrieve the list of videos in the playlist.

**Comment by b5i** [comment]
Hello! It may be the same as #4, do other requests with the provided cookies work?

**Comment by tienmanhsc92** [comment]
> Hello! It may be the same as #4, do other requests with the provided cookies work?

The other requests are still working; only PlaylistInfosResponse is returning a 400 error: "Precondition check failed." I tried it on the Atwy app as well, and it returned the same error.

**Comment by b5i** [comment]
Interesting! Could you activate Atwy's logger and give me the ZIP file containing all the info of the request please? If you don't want to share that kind of private info publicly, disable the show credentials option and send the file to my email address jives-linters.0a@icloud.com.

**Comment by tienmanhsc92** [comment]
What I mean is the playlists in the account of the owner and set to private. I tried changing the playlist mode from private to public, which was successful and allowed me to retrieve the list of videos in that playlist. However, for other private playlists, I encountered the error mentioned earlier.

**Comment by b5i** [comment]
Ok, does the `AccountLibraryResponse` contain the playlist in the `playlists` property?

**Comment by tienmanhsc92** [comment]
Yes. AccountLibraryResponse returns playlists, history, favorites, etc. When I use it to make a request, it returns an error. Here is the code I’m using:
PlaylistInfosResponse.sendNonThrowingRequest(youtubeModel: youtubeModel, data: [.browseId: playlistID], useCookies: true, result: { result in
    switch result {
    case .success(let response):
        completion(response.results, true)
    case .failure(let error):
        print("Error while fetching playlist infos: \(error.localizedDescription)")
        completion(nil, self.detectError())
    }
})

**Comment by b5i** [comment]
I was successfully able to reproduce this issue on my side, I'm going to check that later today. Thank you for the report

**Comment by b5i** [comment]
It should be resolved beginning from commit [`0974be2`](https://github.com/b5i/YouTubeKit/commit/0974be24384e6b379b1ff487bc04f03ee8997e4c), let me know if it still doesn't work for you.
