### ISSUE TITLE
[BUG] - Seeing empty playlists come back

### ISSUE THREAD

**Issue by barfoon** [b5i/YouTubeKit#31]
**EDIT:** Worked itself out here, I am now seeing videos returned again

<hr>

https://youtube.com/playlist?list=PL0mFR_94wMa4m3Gzgb7HcM1jrcA4aFld9

<img width="904" alt="Screenshot 2024-11-09 at 5 55 31 PM" src="https://github.com/user-attachments/assets/b553bbb6-2ae1-49fd-8f63-58f4a761b484">

```
PlaylistInfosResponse.sendNonThrowingRequest(
            youtubeModel: ytModel,
            data: [.browseId : loadedPlaylistId],
            result: { result in
                switch result {
                case .success(let response):
//
                case .failure(let error):
//
                }
            }
        )
```

**Comment by b5i** [comment]
Hello, thank you for raising this issue. 
Unfortunately, I can't access the playlist myself when I'm clicking on your link ("This page isn't available. Sorry about that.
Try searching for something else.") on a web browser.
Is it a private playlist? In this case, could you redo the request in [Atwy](https://www.github.com/b5i/Atwy) and send me the log via email (jives-linters.0a@icloud.com) please?
For that, you have to:
1. Install and compile Atwy (on a simulator or physical device).
2. Activate the logger in the settings.
3. Connect your YouTube account.
4. Go to the account tab -> playlists -> your playlist.
5. If the playlist is shown as empty, go back to the logger menu and send me the ZIP containing the log (no credentials needed). 
Also, make sure that you're using the newest version of YouTubeKit as I fixed a similar issue a few days ago and haven't made a new release.

**Comment by barfoon** [comment]
Thanks @b5i 
Sorry, bad example (not sure what happened to this first one)

Here is a better example of the issue and what I am seeing:

`PL0mFR_94wMa5ExQ_GO_VmBoTTn9PPVPO4`

[https://www.youtube.com/playlist?list=PL0mFR_94wMa5ExQ_GO_VmBoTTn9PPVPO4](https://www.youtube.com/playlist?list=PL0mFR_94wMa5ExQ_GO_VmBoTTn9PPVPO4)

![Screenshot 2024-11-10 at 7 33 48 AM](https://github.com/user-attachments/assets/5c2b0332-55c2-4ff0-a894-155c20336459)

**Comment by barfoon** [comment]
Here is another example: `PL0mFR_94wMa4bbLJhUdBlWugoZ0qkzRUa`

https://www.youtube.com/playlist?list=PL0mFR_94wMa4bbLJhUdBlWugoZ0qkzRUa

![Screenshot 2024-11-10 at 7 46 28 AM](https://github.com/user-attachments/assets/848a74c4-3b4f-4c15-8c4b-9d66927c8046)

**Comment by barfoon** [comment]
> Unfortunately, I can't access the playlist myself

Here's what I see for the very first example now:

`PL0mFR_94wMa4m3Gzgb7HcM1jrcA4aFld9`

[](https://www.youtube.com/playlist?list=PL0mFR_94wMa4m3Gzgb7HcM1jrcA4aFld9)

![Screenshot 2024-11-10 at 7 55 19 AM](https://github.com/user-attachments/assets/c956d47e-4d6d-406d-ae40-b5c4031d0990)

![Screenshot 2024-11-10 at 7 53 32 AM](https://github.com/user-attachments/assets/22902e2f-1712-4096-a1bd-336fe120fc98)

**Comment by b5i** [comment]
Thank you for those examples, it's odd because I can't reproduce the problem on my side. 
Could you test going to the playlist in Atwy (query: "The pwhl toronto sceptres playlist") and see if there's anything on screen?

**Comment by barfoon** [comment]
@b5i Things have worked themselves out here, I am now seeing videos returned again properly. Thanks anyways for your help!
