### ISSUE TITLE
AccountLibraryResponse returns "playlists" as nil on some accounts

### ISSUE THREAD

**Issue by tienmanhsc92** [b5i/YouTubeKit#32]
Hi,
A few days ago, I reported an error where I couldn't request videos in the Playlist, and it was promptly fixed. However, today when requesting the Account (AccountLibraryResponse), the playlist returned nil, even though playlists do exist in my account. I tried creating a few playlists with different privacy settings (public and private), but AccountLibraryResponse still returned the playlist as nil. Watch Later and Favorites still return values.

I also tried logging in with another account, and surprisingly, this account's playlist values are accessible. Not all accounts seem to have this issue. I have debugged and tested it on Atwy, and the result is still the same. 

Please check on this. Thank you!
<img width="2548" alt="Screenshot 2024-11-13 at 13 47 10" src="https://github.com/user-attachments/assets/224c7af4-05ea-4bd1-8713-81e851593aee">

**Comment by b5i** [comment]
Hello! How does the page https://www.youtube.com/feed/you looks like with this account? Does it contain playlists?

**Comment by tienmanhsc92** [comment]
Yes, the playlists are fully available, just like when accessing https://www.youtube.com/feed/playlists

**Comment by b5i** [comment]
Ok, can you send me (jives-linters.0a@icloud.com) the log that Atwy emitted and a screenshot of the webpage please?

**Comment by tienmanhsc92** [comment]
I cannot find the log file in the Documents directory. The error 'Error removing log file: Error Domain=NSCocoaErrorDomain Code=260 "The file “logs” couldn’t be opened because there is no such file."' occurs when I try to delete the logs.

**Comment by tienmanhsc92** [comment]
I debugged and logged the JSON when AccountLibraryResponse was returned. In the loop parsing the JSON to retrieve the playlist, accounts that successfully return playlists contain the key gridPlaylistRenderer. 
<img width="988" alt="Screenshot 2024-11-13 at 14 44 48" src="https://github.com/user-attachments/assets/1a32fed6-31e3-48fd-ba83-fbbf0aa43936">

However, in accounts that return an empty list, this key is missing, and playlist information is instead located in a dictionary with the key lockupViewModel. The keys within this data are entirely different from those in the dictionary with the key gridPlaylistRenderer
<img width="1910" alt="Screenshot 2024-11-13 at 14 39 22" src="https://github.com/user-attachments/assets/86f3cb9a-7107-4e4d-ac45-61a38126f392">

**Comment by b5i** [comment]
Ok that's the kind of change I often have to do with YouTubeKit, can you send the whole JSON of the lookupViewModel so that I can fix YouTubeKit? Also, is the lookupViewModel located at the same place as the gridPlaylistRenderer?

**Comment by b5i** [comment]
> I cannot find the log file in the Documents directory. The error 'Error removing log file: Error Domain=NSCocoaErrorDomain Code=260 "The file “logs” couldn’t be opened because there is no such file."' occurs when I try to delete the logs.

Normally, logs aren't saved in the Documents directory except if you export them (and so it has to create a ZIP file for you to export it), you should be able to access them via the Logger panel in Atwy's settings.

**Comment by b5i** [comment]
> This is the JSON of AccountLibraryResponse returned in the two cases.
> 
> [gridPlaylistRenderer.json](https://github.com/user-attachments/files/17729081/gridPlaylistRenderer.json)
> 
> [lookupViewModel.json](https://github.com/user-attachments/files/17729084/lookupViewModel.json)
> 

Ok thank you, I'll take a look a it later today.

**Comment by tienmanhsc92** [comment]
Ok it worked, the playlist returned successfully. Thank you!
