### ISSUE TITLE
[Feature request] bring the chapters field in VideoInfosResponse

### ISSUE THREAD

**Issue by ldenoue** [b5i/YouTubeKit#6]
Some videos also bring in chapters in the video.
Could this be a new field added to VideoInfosResponse?
https://github.com/b5i/YouTubeKit/blob/1aed7cf4ef662b3ba689ce28f05a8b0f496ed7e6/Sources/YouTubeKit/YouTubeResponseTypes/VideoInfos/VideoInfosResponse.swift#L11

**Comment by b5i** [comment]
Hello! Unfortunately YouTube does not provide the chapter infos of a video in the response of `VideoInfosResponse`, but you can still get them from the [chapters](https://github.com/b5i/YouTubeKit/blob/fb6612d95fe676acae5acd72db4e11e6e239019b/Sources/YouTubeKit/YouTubeResponseTypes/VideoInfos/MoreVideoInfosResponse.swift#L61) attribute of `MoreVideoInfosResponse`!

**Comment by b5i** [comment]
If you want some kind of a big showcase of YouTubeKit's capabilities you can take a look at [Atwy](https://github.com/b5i/Atwy) that takes full advantage of them!
