### ISSUE TITLE
age restricted videos without cookies?

### ISSUE THREAD

**Issue by ldenoue** [b5i/YouTubeKit#7]
Is it possible to get the video info and downloadable urls) on age restricted videos without using cookies?
For example this video https://www.youtube.com/watch?v=Qxx14RCxblg

This `node-ytdl-core` repo had an opened issue on the topic https://github.com/fent/node-ytdl-core/issues/19 and had a fix (which seems broken today)

**Comment by b5i** [comment]
Hello! Thanks for raising all those very interesting issues!!! As far as I know, the connection with a validated account is mandatory to access to the streaming urls of those videos. I'm going to try to find a solution but I can't guarantee anything.

**Comment by ldenoue** [comment]
if at all useful I asked the question to https://github.com/distubejs/ytdl-core/issues/15#issuecomment-1857243107 and was told that apparently it's no longer possible (hopefully you don't care about crossposting)

**Comment by b5i** [comment]
Alright thanks for having looked at the answer!
