### ISSUE TITLE
both downloadFormats and defaultFormats are empty for xUdZhqe2n7w

### ISSUE THREAD

**Issue by ldenoue** [b5i/YouTubeKit#8]
I noticed that xUdZhqe2n7w returns empty arrays for both `downloadFormats` and `defaultFormats` when querying `VideoInfosWithDownloadFormatsResponse`.

However the `streamingData` json contains a `streamingData.formats` entry with 2 values. Could we change the code to use them?

Laurent

**Comment by b5i** [comment]
Alright I think I fixed the bug in this [commit](https://github.com/b5i/YouTubeKit/commit/f15c5e2d4bd60461e9ddd5447bd0ea0d7931ab1f), let me know if it starts working again!

**Comment by ldenoue** [comment]
yes that was it, you are very fast, thank you!
